name: SimpleDropInventory
main: net.shibacraft.simpledropinventory.SimpleDropInventory
version: '${v}'
author: SKJOLBERG
permissions:
  sdi.admin:
    description: Allows all admin permissions
    default: op
  sdi.use:
    description: Allows you to use the command to drop items to the inventory